version: '3.4'

services:

  vhttp:
    image: blackflysolutions/ceratopogonidae:5-php7.4-apache-wordpress
    ports:
      - "80/tcp"
    expose:
      - "80"
    environment:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME
      - VSITE
      - VSITE_DOMAIN
      - VSITE_DOMAIN_ALTERNATIVES
    volumes:
      - vwp:/var/www/html

  vsql:
    image: blackflysolutions/mariadb:10.4
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    volumes:
      - vdb:/var/lib/mysql

  admin:
    image: blackflysolutions/ceratopogonidae:5-php7.4-apache-admin
    volumes:
      - vwp:/var/www/html
    environment:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME
      - VSITE_SITE_NAME
      - VSITE_ADMIN_MAIL
      - VSITE_ADMIN_NAME
      - VSITE
      - VSITE_DOMAIN
      - VSITE_DOMAIN_ALTERNATIVES

    depends_on:
      - vsql
      - vhttp


volumes:
  vwp:
  vdb:
